---
  - hosts: node3
  
    vars_files:
      - ~/pass.yml
  
    tasks:
  
      - name: Install prerequsite packages
        apt: 
          name: "{{item}}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - git
          - gcc
          - git-core
          - python-software-properties
  
      - name: Clone repo
        git:
          repo: https://{{ pass }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v2.git
          dest: /iTrust2-v2
          clone: yes
          force: yes
        become: yes
  
      - name: Add Java8 repository
        apt_repository: 
          repo: ppa:webupd8team/java
          state: present
          update_cache: yes
        become: yes
  
      - name: license agreement select true
        shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
        become: yes
  
      - name: license agreement seen true
        shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
        become: yes
  
      - name: Install Java8
        apt: 
          name: oracle-java8-installer
          state: present
          update_cache: yes
        become: yes
  
      - name: Add Maven repository
        apt_repository: 
          repo: ppa:andrei-pozolotin/maven3
          state: present
          update_cache: yes
        become: yes
  
      - name: Install Maven
        apt: 
          name: maven3
          update_cache: yes
        become: yes
  
      - name: Install mysql
        apt: 
          name: mysql-server-5.5
          state: present
          update_cache: yes
        become: yes
  
      - name: Copy hibernate template file
        copy: 
          remote_src: yes
          src: /iTrust2-v2/iTrust2/src/main/resources/hibernate.properties.template
          dest: /iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
        become: yes
  
      - name: Copy db template file
        copy: 
          remote_src: yes
          src: /iTrust2-v2/iTrust2/src/main/java/db.properties.template
          dest: /iTrust2-v2/iTrust2/src/main/java/db.properties
        become: yes

      - name: Remove spaces in the hibernate file
        replace:
          path: /iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
          regexp: ' = '
          replace: '='
        become: yes
  