---
- hosts: node4

  tasks:

    - name: Install redis server
      apt: 
        name: redis-server
        state: present
        update_cache: yes
      become: yes

    - name: Start the server
      shell: nohup redis-server &
      become: yes

