- name: mvn run
  command: bash -lc "nohup mvn jetty:run &"
  args:
    chdir: /home/ubuntu/iTrust/iTrust2/
  become: yes

- name: MVN Checkstyle
  command: mvn clean test verify checkstyle:checkstyle
  args:
    chdir: /home/ubuntu/iTrust/iTrust2/
  become: yes
