- name: mvn process
  command: bash -lc "mvn process-test-classes"
  args:
    chdir: /home/ubuntu/iTrust/iTrust2/
  become: yes

- name: mvn run
  command: bash -lc "nohup mvn jetty:run &"
  args:
    chdir: /home/ubuntu/iTrust/iTrust2/
  become: yes
