- name: Git clone iTrust
  git: 
    repo: https://{{ GITHUB_USERNAME }}:{{ GITHUB_PASSWORD }}@github.ncsu.edu/engr-csc326-staff/iTrust2-v2.git 
    dest: /home/ubuntu/iTrust2-v2/
    force: yes
  become: yes

- name: Copy hibernate template file
  copy: 
    remote_src: yes
    src: /home/ubuntu/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties.template
    dest: /home/ubuntu/iTrust2-v2/iTrust2/src/main/resources/hibernate.properties
  become: yes

- name: Copy db template file
  copy: 
    remote_src: yes
    src: /home/ubuntu/iTrust2-v2/iTrust2/src/main/java/db.properties.template
    dest: /home/ubuntu/iTrust2-v2/iTrust2/src/main/java/db.properties
  become: yes

- name: Copy email template file
  template: 
    src: ./roles/iTrust/files/email.properties
    dest: /home/ubuntu/iTrust2-v2/iTrust2/src/main/java/email.properties
  become: yes

- name: Copy pom-data.xml
  copy: 
    src: ./roles/iTrust/files/pom-data.xml
    dest: /home/ubuntu/iTrust2-v2/iTrust2/pom-data.xml
  become: yes

- name: Add skip-grant-tables in my.cnf
  blockinfile:
    path: /etc/mysql/my.cnf
    block:  |
      [mysqld]
      skip-grant-tables
  become: true 

- name: start the mysql service
  service: 
    name: mysql
    state: restarted
  become: yes

- name: Copy Jenkins jobs config
  copy:
    src: ./roles/iTrust/files/itrust.yml
    dest: /var/lib/jenkins/itrust.yml
    mode: 777
  become: yes

- name: Create iTrust's build job on Jenkins server using Jenkins Job Builder
  command: jenkins-jobs update /var/lib/jenkins/itrust.yml
  become: yes

- name: Build iTrust's job
  command: java -jar "{{ jenkins_jar_location }}" -s http://"{{ jenkins_hostname }}":"{{ jenkins_port }}" build itrust
  become: yes