- name: git clone
  git: 
    repo: https://github.com/chrisparnin/checkbox.io.git
    dest: /home/ubuntu/checkbox/
    force: yes
  become: yes

- name: copy nginx.conf
  copy: 
    remote_src: yes
    src: /home/ubuntu/checkbox/local-conf/nginx.conf 
    dest: /etc/nginx/nginx.conf
  become: yes

- name: copy default
  copy:
    remote_src: yes
    src: /home/ubuntu/checkbox/local-conf/default 
    dest: /etc/nginx/sites-available/default
  become: yes

- name: Modify checkbox.io
  replace:
    path: /etc/nginx/sites-available/default
    regexp: '/Users/gameweld/bitbucket/checkbox.io/checkbox.io/public_html/'
    replace: '/home/ubuntu/checkbox/public_html'
  become: yes

- name: npm Install
  npm:
    path: /home/ubuntu/checkbox/server-side/site/
  become: yes
