---
- name: Install MySQL
  apt: 
    name: mysql-server
    state: present
    update_cache: yes

- name: Add skip-grant-tables in my.cnf
  blockinfile:
    path: /etc/mysql/my.cnf
    block:  |
      [mysqld]
      skip-grant-tables
      bind-address = 0.0.0.0
  become: true 

- name: Start MySQL service
  service: 
    name: mysql
    state: restarted
  become: yes

# - name: Install ufw
#   apt:
#     name: ufw
#     state: latest
#     update_cache: yes

# - name: Open MySQL port via ufw
#   ufw:
#     rule: allow
#     port: '3306'
#     state: reloaded

# - name: Enable firewall
#   shell: ufw enable

# - name: Export the current state of MySQL from jenkins server
#   local_action: "shell mysqldump iTrust2 > /tmp/itrust.sql"

# - name: Copy the captured state to the server
#   copy:
#     src: /tmp/itrust.sql
#     dest: /tmp/itrust.sql

# - name: Create itrust database if it doesn't exist on MySQL server
#   command: mysql -u root --execute "CREATE DATABASE IF NOT EXISTS iTrust2;"

# - name: Import the state of MySQL from jenkins server
#   shell: mysql iTrust2 < /tmp/itrust.sql