---
- name: Install MySQL
  apt: 
    name: mysql-server
    state: present
    update_cache: yes

- name: Add skip-grant-tables in my.cnf
  blockinfile:
    path: /etc/mysql/my.cnf
    block:  |
      [mysqld]
      skip-grant-tables
  become: true 

- name: Start MySQL service
  service: 
    name: mysql
    state: restarted
  become: yes

- name: Install ufw
  apt:
    name: ufw
    state: latest
    update_cache: yes

- name: Open MySQL port via ufw
  ufw:
    rule: allow
    port: '3306'
    state: reloaded

- name: Export the current state of MySQL from jenkins server
  local_action: "shell mysqldump itrust > /tmp/itrust.sql"

- name: Copy the captured state to the server
  copy:
    src: /tmp/itrust.sql
    dest: /tmp/itrust.sql

- name: Create itrust database if it doesn't exist on MySQL server
  command: mysql -u root --execute "CREATE DATABASE IF NOT EXISTS itrust;"

- name: Import the state of MySQL from jenkins server
  shell: mysql itrust < /tmp/itrust.sql