---
- name: Create load balancer directory
  file: path=/home/ubuntu/loadbalancer state=directory

- name: Copy load balancer script
  copy:
    remote_src: yes
    src: /home/ubuntu/CSC519DevOps-Project/src/roles/loadbalancer/files/{{ item }}
    dest: /home/ubuntu/loadbalancer/{{ item }}
    force: yes
  with_items:
  - loadbalancer.js
  - package.json
  become: yes

- name: npm install
  npm:
    path: /home/ubuntu/loadbalancer/
  become: yes

- name: Run load balancer
  shell: nohup node loadbalancer.js &
  chdir: /home/ubuntu/loadbalancer/
