---
MONGO_PORT: "{{ lookup('env', 'MONGO_PORT') }}"
MONGO_IP: "{{ lookup('env', 'MONGO_IP') }}"
MONGO_USER: "{{ lookup('env', 'MONGO_USER') }}"
MONGO_PASSWORD: "{{ lookup('env', 'MONGO_PASSWORD') }}"
GITHUB_NAME: "{{ lookup('env', 'GITHUB_NAME') }}"
GITHUB_EMAIL: "{{ lookup('env', 'GITHUB_EMAIL') }}"
GITHUB_USERNAME: "{{ lookup('env', 'GITHUB_USERNAME') }}"
GITHUB_PASSWORD: "{{ lookup('env', 'GITHUB_PASSWORD') }}"
MAIL_FROM: "{{ lookup('env', 'MAIL_FROM') }}"
MAIL_USER: "{{ lookup('env', 'MAIL_USER') }}"
MAIL_PASSWORD: "{{ lookup('env', 'MAIL_PASSWORD') }}"
MAIL_SMTP: "{{ lookup('env', 'MAIL_SMTP') }}"
AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
AWS_ACCESS_KEY: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
AWS_SECRET_KEY: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
AWS_KEY_PAIR: "{{ lookup('env', 'AWS_KEY_PAIR') }}"
AWS_SSH_KEY: "{{ lookup('env', 'AWS_SSH_KEY') }}"

role_home: "/home/ubuntu/CSC519DevOps-Project/src/roles"
aws_role: "{{ role_home }}/aws"
jenkins_role: "{{ role_home }}/jenkins"
checkbox_role: "{{ role_home }}/checkbox"
itrust_role: "{{ role_home }}/itrust"
local_templates: "/home/ubuntu/templates/"
itrust_war: "/home/ubuntu/iTrust2-v2/iTrust2/target/iTrust2.war"