---
- name: Create AWS key
  ec2_key:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    name: "{{ keypair }}"
    region: "{{ region }}"
    state: present
  register: ec2_i

- name: Generate AWS private key
  copy:
    content: "{{ ec2_i.key.private_key }}"
    dest: ~/.ssh/jenkins.key
    mode: 0600

- name: Create EC2 Instance
  local_action: ec2
                image={{ image }}
                instance_type={{ instance_type }}
                group={{ security_group }}
                region={{ region }}
                keypair={{ keypair }}
                count={{ count }}
                wait=true
  register: ec2

- name: Update in memory inventory file
  add_host:
    groups: jenkins
    hostname: "jenkins-server-{{ ec2.instances[0].public_ip }}"
    ansible_ssh_user: "ubuntu"
    ansible_ssh_private_key_file: "~/.ssh/jenkins.key"
    ansible_python_interpreter: "/usr/bin/python3"
    host_key_checking: "False"

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ ec2.instances[0].public_ip }}"
    port: 22
    timeout: 320
    state: started
