---
- hosts: checkbox

  vars:
    MONGO_PORT: "{{ lookup('env', 'MONGO_PORT') }}"
    MONGO_IP: "{{ lookup('env', 'MONGO_IP') }}"
    MONGO_USER: "{{ lookup('env', 'MONGO_USER') }}"
    MONGO_PASSWORD: "{{ lookup('env', 'MONGO_PASSWORD') }}"
    # MAIL_USER: "{{ lookup('env', 'MAIL_USER') }}"
    # MAIL_PASSWORD: "{{ lookup('env', 'MAIL_PASSWORD') }}"
    # MAIL_SMTP: "{{ lookup('env', 'MAIL_SMTP') }}"
  
  roles: 
  - dependencies
  - repo&config
  - run