---
- name: Provision Jenkins server
  hosts: jenkins
  become: yes 
  roles:
    - jenkins

- name: Create EC2 instances
  hosts: jenkins
  become: false
  roles:
    - aws

- name: Provision iTrust server
  hosts: jenkins
  become: yes 
  roles:
    - itrust
    # - checkbox
