---
- name: Provision Jenkins server
  hosts: jenkins
  become: yes 
  roles:
    - jenkins
    # - itrust
    # - checkbox

- name: Create EC2 instances
  hosts: jenkins
  become: false
  roles:
    - aws