- job:
    block-downstream: false
    block-upstream: false
    builders:
    - shell: cd /home/ubuntu/iTrust2-v2/iTrust2 && mvn process-test-classes && mvn clean test verify checkstyle:checkstyle
    concurrent: false
    description: iTrust2's Build job
    disabled: false
    name: !!python/unicode 'itrust'
    project-type: freestyle
    publishers:
    - raw:
        xml: |
          <hudson.tasks.junit.JUnitResultArchiver plugin="junit@1.24">
          <testResults>**/iTrust2-v2/iTrust2/target/surefire-reports/*.xml</testResults>
          <keepLongStdio>true</keepLongStdio>
          <healthScaleFactor>1.0</healthScaleFactor>
          <allowEmptyResults>true</allowEmptyResults>
          </hudson.tasks.junit.JUnitResultArchiver>
    - raw:
        xml: |
          <hudson.plugins.jacoco.JacocoPublisher plugin="jacoco@3.0.1">
          <execPattern>**/**.exec</execPattern>
          <classPattern>**/classes</classPattern>
          <sourcePattern>**/src/</sourcePattern>
          <inclusionPattern />
          <exclusionPattern />
          <skipCopyOfSrcFiles>false</skipCopyOfSrcFiles>
          <minimumInstructionCoverage>0</minimumInstructionCoverage>
          <minimumBranchCoverage>0</minimumBranchCoverage>
          <minimumComplexityCoverage>0</minimumComplexityCoverage>
          <minimumLineCoverage>0</minimumLineCoverage>
          <minimumMethodCoverage>0</minimumMethodCoverage>
          <minimumClassCoverage>0</minimumClassCoverage>
          <maximumInstructionCoverage>0</maximumInstructionCoverage>
          <maximumBranchCoverage>0</maximumBranchCoverage>
          <maximumComplexityCoverage>0</maximumComplexityCoverage>
          <maximumLineCoverage>0</maximumLineCoverage>
          <maximumMethodCoverage>0</maximumMethodCoverage>
          <maximumClassCoverage>0</maximumClassCoverage>
          <changeBuildStatus>false</changeBuildStatus>
          <deltaInstructionCoverage>0</deltaInstructionCoverage>
          <deltaBranchCoverage>0</deltaBranchCoverage>
          <deltaComplexityCoverage>0</deltaComplexityCoverage>
          <deltaLineCoverage>0</deltaLineCoverage>
          <deltaMethodCoverage>0</deltaMethodCoverage>
          <deltaClassCoverage>0</deltaClassCoverage>
          <buildOverBuild>false</buildOverBuild>
          </hudson.plugins.jacoco.JacocoPublisher>
    triggers: []
    wrappers: []