---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - gcc
    - make
    - libc6-dev

- name: Download Redis
  apt_repository:
    repo: 'ppa:chris-lea/redis-server'
    state: present

- name: update cache
  apt:
    update_cache: yes
  changed_when: False

- name: Ensure Redis present
  apt:
    pkg: redis-server
    state: latest

- name: Start Redis
  service:
    name: redis
    state: started

- name: Find IP Address
  command: grep "bind 127.0.0.1" /etc/redis/redis.conf
  ignore_errors: True
  changed_when: False

- name: Change IP Address
  replace:
    regexp: 'bind 127.0.0.1' 
    replace: '# bind 127.0.0.1'
    dest: /etc/redis/redis.conf

- name: Add tcpkeepalive parameter
  replace:
    regexp: 'tcp-keepalive 300'
    replace: 'tcp-keepalive 60'
    dest: /etc/redis/redis.conf

- name: master-add password
  replace:
    regexp: '# requirepass foobared'
    replace: 'requirepass password'
    dest: /etc/redis/redis.conf

- name: master-update maxmemory-policy
  replace:
    regexp: '# maxmemory-policy noeviction'
    replace: 'maxmemory-policy noeviction'
    dest: /etc/redis/redis.conf

- name: master-update appendonly
  replace:
    regexp: 'appendonly no'
    replace: 'appendonly yes'
    dest: /etc/redis/redis.conf

- name: master-update file
  replace:
    regexp: 'appendfilename "appendonly.aof"'
    replace: 'appendfilename "redis-staging-ao.aof"'
    dest: /etc/redis/redis.conf

- name: Restart redis service
  shell: sudo /etc/init.d/redis-server restart

- name: npm install
  command: npm install
  args:
    chdir: /home/ubuntu/CSC519DevOps-Project/src/redis/

- name: Run redis feature flag script
  command: bash -lc "nohup node redis.js &"
  args: 
    chdir: /home/ubuntu/CSC519DevOps-Project/src/redis/
 