---  
- name: Add skip-grant-tables in my.cnf
  blockinfile:
    path: /etc/mysql/my.cnf
    block:  |
      [mysqld]
      skip-grant-tables
  become: true 

- name: Start MySQL service
  service: 
    name: mysql
    state: restarted
  become: yes

- name: Set GitHub credentials
  set_fact:
    github_username: "{{ GITHUB_USERNAME }}"
    github_password: "{{ GITHUB_PASSWORD }}"

- name: Create iTrust's job file
  template:
    src: itrust.yml.j2
    dest: /home/vagrant/CSC519DevOps-Project/jenkins/roles/itrust/files/itrust.yml

- name: Create job on Jenkins using Jenkins Job Builder
  command: jenkins-jobs update /home/vagrant/CSC519DevOps-Project/jenkins/roles/itrust/files/itrust.yml
