- name: Get nodejs 9.x setup
  shell: curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

- name: Install nodejs
  update_cache: yes
  apt:
    name: nodejs
  become: yes
  force: yes

- name: Add mongo ppa key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present 
  become: yes

- name: Add mongo sources list
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse"
    state: present
  become: yes

- name: Install mongodb 3.6
  update_cache: yes
  apt:
    name: mongodb-org
    state: latest
  become: yes
  force: yes

- name: Install dependencies
  update_cache: yes
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - nginx
    - python-pip
  become: yes

- name: Install pymongo
  pip:
    name: pymongo
    version: 3.6.0
    use_mirrors: no
  become: yes