---  
- name: Set MongoDB IP
  blockinfile:
    path: /etc/environment
    block: |
      MONGO_IP={{ mongo }}
    create: yes
    state: present

- name: Update the bash profile
  shell: . /etc/environment

- name: Restart Jenkins
  service:
    name: jenkins 
    state: restarted

- name: Create checkbox's job file
  template:
    src: checkbox.yml.j2
    dest: /home/ubuntu/CSC519DevOps-Project/src/roles/deploy-checkbox/files/checkbox.yml

- name: Create job on Jenkins using Jenkins Job Builder
  command: jenkins-jobs update /home/ubuntu/CSC519DevOps-Project/src/roles/deploy-checkbox/files/checkbox.yml
