---  
- name: Create checkbox's job file
  template:
    src: checkbox.yml.j2
    dest: /home/vagrant/CSC519DevOps-Project/src/roles/deploy-checkbox/files/checkbox.yml

- name: Create job on Jenkins using Jenkins Job Builder
  command: jenkins-jobs update /home/vagrant/CSC519DevOps-Project/src/roles/deploy-checkbox/files/checkbox.yml
