---
- name: Deploy checkbox.io canary server
  hosts: checkbox
  vars:
    MONGO_PORT: "{{ lookup('env', 'MONGO_PORT') }}"
    MONGO_IP: "{{ lookup('env', 'MONGO_IP') }}"
    MONGO_USER: "{{ lookup('env', 'MONGO_USER') }}"
    MONGO_PASSWORD: "{{ lookup('env', 'MONGO_PASSWORD') }}"
  become: yes
  serial: 1
  gather_facts: no
  roles:  
  - nodejs 
  - dependencies
  - repo&config
  - run
