---
- name: Provision Jenkins server
  hosts: jenkins
  become: yes 
  roles:
    - server-jenkins

- name: Create EC2 instances
  hosts: jenkins
  become: false
  roles:
    - create-ec2

- name: Deploy iTrust
  hosts: jenkins
  become: yes 
  roles:
    - deploy-itrust

- name: Deploy checkbox.io
  hosts: jenkins
  become: yes 
  roles:
    - deploy-checkbox