---
- name: Create EC2 Instances
  local_action: ec2
                image={{ image }}
                instance_type={{ instance_type }}
                group={{ security_group }}
                region={{ region }}
                keypair={{ keypair }}
                count={{ count }}
                wait=true
  register: ec2

- name: Update EC2 IP list
  set_fact:
    proxy: "{{ ec2.instances[0].public_ip }}"
    host1: "{{ ec2.instances[1].public_ip }}"
    host2: "{{ ec2.instances[2].public_ip }}"
    host3: "{{ ec2.instances[3].public_ip }}"
    host4: "{{ ec2.instances[4].public_ip }}"
    host5: "{{ ec2.instances[5].public_ip }}"

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ item.public_ip }}"
    port: 22
    timeout: 320
    state: started
  with_items:
    "{{ ec2.instances }}"

- name: Copy IP addresses of those EC2 instances
  template:
    src: ec2_ip_list.j2
    dest: /home/vagrant/ec2_ip_list